export default [
    {
        files: ['**/*.js'],
        ignores: ['node_modules/**', 'tests/**', 'vitest.config.js', 'eslint.config.js'],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'script',
            globals: {
                // Browser globals
                window: 'readonly',
                document: 'readonly',
                localStorage: 'readonly',
                sessionStorage: 'readonly',
                navigator: 'readonly',
                fetch: 'readonly',
                URL: 'readonly',
                URLSearchParams: 'readonly',
                console: 'readonly',
                setTimeout: 'readonly',
                setInterval: 'readonly',
                clearTimeout: 'readonly',
                clearInterval: 'readonly',
                Promise: 'readonly',
                crypto: 'readonly',
                history: 'readonly',
                self: 'readonly',
                SharedWorker: 'readonly',
                Map: 'readonly',
                Set: 'readonly',
                screen: 'readonly',
                module: 'readonly',
                Uint8Array: 'readonly',
                Array: 'readonly',
                Date: 'readonly',
                JSON: 'readonly',
                Error: 'readonly',
                MutationObserver: 'readonly',
                IntersectionObserver: 'readonly',
                Node: 'readonly',
                requestAnimationFrame: 'readonly',
                CustomEvent: 'readonly',
                HTMLElement: 'readonly',
                Event: 'readonly',
                FormData: 'readonly',
                Blob: 'readonly',
                FileReader: 'readonly',
                Image: 'readonly',
                XMLHttpRequest: 'readonly',
                confirm: 'readonly',
                prompt: 'readonly',
                // App shared globals
                ConfirmModal: 'readonly',
                PromptModal: 'readonly',
                CloudStorage: 'writable',
                EnvConfig: 'writable',
                AuthGuard: 'writable',
                TokenManager: 'writable',
                RoleGuard: 'writable',
                SyncManager: 'writable',
                Toast: 'readonly',
                ErrorHandler: 'readonly',
                Utils: 'writable',
                StorageManager: 'writable',
                RolesConfig: 'readonly',
                LocalIcons: 'readonly',
                lucide: 'readonly',
                AboutModal: 'writable',
                AppVersion: 'writable',
                ComponentLoader: 'writable',
                PageLifecycle: 'writable',
                SidebarController: 'writable',
                // Module-specific globals
                storage: 'writable',
                Documentation: 'writable',
                StepsNavigator: 'writable',
                // excel-reports
                ExcelJS: 'readonly',
                XLSX: 'readonly',
                ExcelReportsUtils: 'writable',
                FileProcessor: 'writable',
                StateManager: 'writable',
                UIRenderer: 'writable',
                logger: 'writable',
                // team-info
                TeamAvatars: 'writable',
                TeamForms: 'writable',
                TeamImportExport: 'writable',
                TeamInvites: 'writable',
                TeamNavigation: 'writable',
                TeamRenderer: 'writable',
                TeamState: 'writable',
                TeamTemplates: 'writable',
                TeamUtils: 'writable'
            }
        },
        rules: {
            'no-unused-vars': ['warn', { argsIgnorePattern: '^_', caughtErrors: 'none' }],
            'no-undef': 'error',
            'no-redeclare': 'off',
            'eqeqeq': ['warn', 'smart'],
            'no-eval': 'error',
            'no-implied-eval': 'error',
            'no-new-func': 'error'
        }
    }
];
